### ISSUE TITLE
Transfer to broccolijs repo

### ISSUE THREAD

**Issue by sandstrom** [folz/broccoli-site#5]
@folz This is a great website you've built! ⛵️ 

Would you mind transferring this to the broccolijs repo? Would make it easier for others to know where the website source is, and to contribute PRs.

joliss seems to be open to it: https://github.com/broccolijs/broccoli/issues/222#issuecomment-72333891

**Comment by folz** [comment]
Thanks, I'd forgotten about this. Continuing the conversation over there.
